fix: pipeline github action

diff --git a/.github/workflows/main_monitorcontrol.yml b/.github/workflows/main_monitorcontrol.yml
--- a/.github/workflows/main_monitorcontrol.yml
+++ b/.github/workflows/main_monitorcontrol.yml
@@ -1,7 +1,7 @@
 # Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
 # More GitHub Actions for Azure: https://github.com/Azure/actions
 
-name: Build and deploy JAR app to Azure Web App - MonitorControl
+name: Build and deploy Next.js app to Azure Web App - MonitorControl
 
 on:
   push:
@@ -12,30 +12,44 @@ on:
 jobs:
   build:
     runs-on: ubuntu-latest
-    permissions:
-      contents: read #This is required for actions/checkout
 
     steps:
-      - uses: actions/checkout@v4
+    - uses: actions/checkout@v4
 
-      - name: Set up Java version
-        uses: actions/setup-java@v4
-        with:
-          java-version: '21'
-          distribution: 'microsoft'
+    - name: Set up Node.js version
+      uses: actions/setup-node@v4
+      with:
+        node-version: '18.x'
+        cache: 'npm'
 
-      - name: Build with Maven
-        run: mvn clean install
+    - name: npm install, build, and test
+      env:
+        SMTP_USER: ${{ secrets.SMTP_USER }}
+        SMTP_PASS: ${{ secrets.SMTP_PASS }}
+      run: |
+        npm ci
+        npm run build
+        npm run export || echo "Export command not found, skipping"
+      working-directory: .
 
-      - name: Upload artifact for deployment job
-        uses: actions/upload-artifact@v4
-        with:
-          name: java-app
-          path: '${{ github.workspace }}/target/*.jar'
+    - name: Upload artifact for deployment job
+      uses: actions/upload-artifact@v4
+      with:
+        name: node-app
+        path: |
+          package.json
+          package-lock.json
+          next.config.js
+          public/
+          .next/
+          node_modules/
 
   deploy:
     runs-on: ubuntu-latest
     needs: build
+    environment:
+      name: Production
+      url: https://monitorcontrol.azurewebsites.net
     permissions:
       id-token: write #This is required for requesting the JWT
       contents: read #This is required for actions/checkout
@@ -44,7 +58,7 @@ jobs:
       - name: Download artifact from build job
         uses: actions/download-artifact@v4
         with:
-          name: java-app
+          name: node-app
       
       - name: Login to Azure
         uses: azure/login@v2
@@ -59,5 +73,4 @@ jobs:
         with:
           app-name: 'MonitorControl'
           slot-name: 'Production'
-          package: '*.jar'
-          
+          package: .
